### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ricardokleinklein** [ricardokleinklein/diabetes_forecasting#1]
# Data loading
- [ ] Time processing
- [ ] Time conversion
- [ ] Input data from data source 1.
- [ ] Input data from data source 2.

# Preprocessing
- [ ] Evaluate distribution of attributes
- [ ] Select valuable features
- [ ] Detect signals of interest in the main attribute
